
version: "3.8"

services:
  minecraft:
    image: openjdk:8-jre-slim
    restart: unless-stopped
    volumes:
      - serverdata:/data  # Path on host machine : Path in container
    environment:
      EULA: TRUE  # Minecraft server EULA agreement
    ports:
      - "25565:25565"  # Minecraft server port
    command:
      [ "bash", "-c", "unzip -q /tmp/server.zip && exec java -Xmx14G -Xms14G -jar minecraft_server.1.12.2.jar" ]
    depends_on:
      - downloader

  downloader:
    image: alpine:latest
    restart: unless-stopped
    command:
      [ "sh", "-c", "curl -L https://storage.googleapis.com/dikeman-mc-patched/mce_server_patched.zip -o /tmp/server.zip" ]

volumes:
  serverdata: ./minecraft-data  # Example path on host machine 
